### ISSUE TITLE
How to setup vnc viewer with wrench?

### ISSUE THREAD

**Issue by alekcacko** [SmartisanTech/Wrench#3]
I want to setup vnc viewer for Wrench, the hard part for me is getting QT vnc viewer on Ubuntu 16.04 LTS.

Can you tell me?

**Comment by baohaojun** [comment]
Hi, it has been added in the readme.


Suppose you have compiled Wrench for Ubuntu16.04, now basically you need to compile an androidvncserver for your phone first. Or maybe you can tell me your phone's ro.build.version.sdk prop value and _uname -m_ output, and let me see if I can upload a prebuilt version.
