### ISSUE TITLE
一加三H2OS系统重复提示需要安装辅助APK

### ISSUE THREAD

**Issue by HachikoDream** [SmartisanTech/Wrench#4]
机型：oneplus3
系统：H2OS2.0 pc：mac
现象：mac一直弹框提示需要安装辅助apk，请允许
info: 小扳手辅助apk安装成功
info: 小扳手辅助apk安装成功

**Comment by baohaojun** [comment]
帮忙调试一下，底下的规则比较简单的，先安装APK，安装成功的话，会push一个.md5文件到手机上。下次发现这个.md5文件存在，并且里面的md5值与当前PC上的md5值相等的话，就不会再提示安装APK了。

目前手上没有1加3，没法调试啊...

**Comment by HachikoDream** [comment]
恩 搞定了 手机系统6.0 默认没给任何权限，把权限都给了就好了

**Comment by baohaojun** [comment]
谢谢，😃。我将关闭此Bug。
