### ISSUE TITLE
archlinux安装小扳手

### ISSUE THREAD

**Issue by Qing1997** [SmartisanTech/Wrench#5]
不好意思打扰了，我是一个小白，在安装小扳手的时候出现了很多问题，当我执行。./build-linux.sh的时候，出现了以下问题：qtchooser: could not find a Qt installation of '5'，其实qtchooser一开始也是没有的，我在github上下下来的，然后就这样了，我安装了qt5了，但不知道是怎么回事，很抱歉给您添麻烦了，希望您能够在百忙之中抽出时间回答一下我的问题，不胜感激！

**Comment by baohaojun** [comment]
这类问题你自己上Google搜应该会更方便一些哦。就是有些依赖包没装上导致的。

**Comment by baohaojun** [comment]
对了，你说自己从GitHub上下载安装了qtchooser，这对初学者来说不大好，建议尽量用系统自带的安装包管理系统解决。
